<?php
function moon_ui_cpt_creative_brief() {
	$labels = [
		'name'                  => 'Creative Briefs',
		'singular_name'         => 'Creative Brief',
		'menu_name'             => 'Creative Briefs',
		'name_admin_bar'        => 'Creative Brief',
		'archives'              => 'Creative Brief Archives',
		'attributes'            => 'Creative Brief Attributes',
		'parent_item_colon'     => 'Parent Creative Brief:',
		'all_items'             => 'All Creative Briefs',
		'add_new_item'          => 'Add New Creative Brief',
		'add_new'               => 'Add New',
		'new_item'              => 'New Creative Brief',
		'edit_item'             => 'Edit Creative Brief',
		'update_item'           => 'Update Creative Brief',
		'view_item'             => 'View Creative Brief',
		'view_items'            => 'View Creative Briefs',
		'search_items'          => 'Search Creative Brief',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into creative brief',
		'uploaded_to_this_item' => 'Uploaded to this creative brief',
		'items_list'            => 'Creative briefs list',
		'items_list_navigation' => 'Creative briefs list navigation',
		'filter_items_list'     => 'Filter creative briefs list',
	];
	$args = [
		'label'                 => 'Creative Brief',
		'description'           => 'Creative Brief',
		'labels'                => $labels,
		'supports'              => ['title', 'editor', 'excerpt', 'thumbnail', 'custom-fields', 'page-attributes', 'post-formats'],
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 20,
		'menu_icon'             => 'dashicons-clipboard',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	];
	register_post_type('creative-brief', $args);

}
add_action('init', 'moon_ui_cpt_creative_brief', 0);
